### PR TITLE
arch: add RISCV support

### PR DESCRIPTION
**Pull request by espressif2022**
add RISCV support for esp32-c3/c3/c6.

### CODE REVIEW

**Comment by espressif2022** [comment]
I don’t know where the file cppcheck failed, can you help me to look it up.

**Comment by chmorgan** [comment]
Hey @espressif2022 I missed this until today, sorry about that. Yes of course, I'll take a look and help get this working tonight.

**Comment by chmorgan** [comment]
@espressif2022 would you mind rebasing against main and pushing? I'd like to see if the cppcheck v1.4 actions either fixes the issue or lets us see what is going on. In any case, the changes look good and I'll merge in the near future.

**Comment by espressif2022** [comment]
> @espressif2022 would you mind rebasing against main and pushing? I'd like to see if the cppcheck v1.4 actions either fixes the issue or lets us see what is going on. In any case, the changes look good and I'll merge in the near future.

cppcheck v1.4 is ok, thanks.

**Comment by chmorgan** [comment]
Thank you for the pr, merged.

**Comment by espressif2022** [comment]
> Thank you for the pr, merged.

OK, look forward to the update of the new components version.

**Comment by chmorgan** [comment]
@espressif2022 v1.0.5 pushed to components repository. Thanks for the contribution, there haven't been too many so far, hoping that's because its working well for people.

**Pull request merged**
